// VISUALS
export const LOADING = "LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// PRODUCTS
export const ADD_TO_CART = "ADD_TO_CART";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";
export const GET_CURRENT_PRODUCT = "GET_CURRENT_PRODUCT";
export const CLEAR_CURRENT_PRODUCT = "CLEAR_CURRENT_PRODUCT";
export const ADD_NEW_REVIEW = "ADD_NEW_REVIEW";
export const CLEAR_REDUCER = "CLEAR_REDUCER";
export const STOP_PAGINATION = "STOP_PAGINATION";
