// PRODUCTS
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";
export const CLEAR_CATEGORIES = "CLEAR_CATEGORIES";
export const GET_CURRENT_PRODUCT = "GET_CURRENT_PRODUCT";
export const CLEAR_CURRENT_PRODUCT = "CLEAR_CURRENT_PRODUCT";
export const ADD_NEW_REVIEW = "ADD_NEW_REVIEW";
export const ADD_NEW_COMMENT = "ADD_NEW_COMMENT";
export const CLEAR_REDUCER = "CLEAR_REDUCER";
export const STOP_PAGINATION = "STOP_PAGINATION";
export const PREVIOUS_PAGE = "PREVIOUS_PAGE";
export const NEXT_PAGE = "NEXT_PAGE";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const CHANGE_PRODUCT = "CHANGE_PRODUCT";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"; // FUL PROIZVODI
export const CLEAR_ALL_PRODUCTS = "CLEAR_ALL_PRODUCTS";
export const GET_LATEST_PRODUCTS = "GET_LATEST_PRODUCTS";
export const CLEAR_LATEST_PRODUCTS = "CLEAR_LATEST_PRODUCTS";

// VISUALS
export const LOADING = "LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// USER
export const GET_PROFILE = "GET_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const ADD_TO_GUEST_CART = "ADD_TO_GUEST_CART";
export const ADD_TO_USER_CART = "ADD_TO_USER_CART";
export const REMOVE_FROM_GUEST_CART = "REMOVE_FROM_GUEST_CART";
export const REMOVE_FROM_USER_CART = "REMOVE_FROM_USER_CART";
export const ADD_TO_USER_FAVS = "ADD_TO_USER_FAVS";
export const REMOVE_FROM_USER_WISHLIST = "REMOVE_FROM_USER_WISHLIST";
export const SAVE_GUEST_INFO = "SAVE_GUEST_INFO";
export const SAVE_DELPAY = "SAVE_DELPAY";
export const INCREMENT_GUEST_PRODUCT = "INCREMENT_GUEST_PRODUCT";
export const DECREMENT_GUEST_PRODUCT = "DECREMENT_GUEST_PRODUCT";
export const USER_PRODUCT_QUANTITY = "USER_PRODUCT_QUANTITY";
export const CLEAN_USER = "CLEAN_USER";
export const CLEAN_GUEST = "CLEAN_GUEST";
export const USER_PURCHASE = "USER_PURCHASE";
export const GUEST_PURCHASE = "GUEST_PURCHASE";
export const GET_ORDER_ITEMS = "GET_ORDER_ITEMS";
export const CLEAR_ORDERS = "CLEAR_ORDERS";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const CLEAR_ALL_ORDERS = "CLEAR_ALL_ORDERS";
export const REMOVE_ORDER = "REMOVE_ORDER";
export const GET_WISHLIST = "GET_WISHLIST";
export const ADD_TO_USER_WISHLIST = "ADD_TO_USER_WISHLIST";
export const GET_ORDER_ID = "GET_ORDER_ID";
export const CLEAR_DELPAY = "CLEAR_DELPAY";
export const GUEST_PRODUCT_QUANTITY = "GUEST_PRODUCT_QUANTITY";

// AUTH
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTO_SIGNIN_SUCCESS = "AUTO_SIGNIN_SUCCESS";
export const AUTO_SIGNIN_FAIL = "AUTO_SIGNIN_FAIL";
export const LOGOUT = "LOGOUT";
export const NEW_ACCESS_TOKEN = "NEW_ACCESS_TOKEN";
